bash scripts: replace indentation 4 spaces with tabs (unexpand -t 4)

diff --git a/install-fedora b/install-fedora
--- a/install-fedora
+++ b/install-fedora
@@ -14,9 +14,9 @@ dnf install rpm-build || exit 1
 
 myPath="$0"
 if [ "${myPath:0:2}" == "./" ] ; then
-    myPath=$PWD${myPath:1}
+	myPath=$PWD${myPath:1}
 elif [ "${myPath:0:1}" != "/" ] ; then
-    myPath=$PWD/$myPath
+	myPath=$PWD/$myPath
 fi
 
 
@@ -83,20 +83,20 @@ and Indian National calendars, as well as common English(Gregorian) calendar
 rpmbuild -bb $pkgName.spec
 status=$?
 if [ "$status" != "0" ] ; then
-    echo "rpmbuild exited with failed status '$status'"
-    exit $status
+	echo "rpmbuild exited with failed status '$status'"
+	exit $status
 fi
 
 pkgPath="/root/rpmbuild/RPMS/noarch/$pkgName-$version-1.noarch.rpm"
 
 if [ ! -f $pkgPath ] ; then
-    echo "rpmbuild exited with success status $rpmbuild_status, but no package file was found"
-    exit 1
+	echo "rpmbuild exited with success status $rpmbuild_status, but no package file was found"
+	exit 1
 fi
 
 if [ ! -f $pkgPath ] ; then
-    echo "Package file $pkgPath does not exit"
-    exit 1
+	echo "Package file $pkgPath does not exit"
+	exit 1
 fi
 
 echo "Package created in \"$pkgPath\", installing"
diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -1,15 +1,15 @@
 #!/bin/bash
 
 function printUsage {
-    echo "Usage: $0 [--prefix=/usr/local]"
+	echo "Usage: $0 [--prefix=/usr/local]"
 }
 
 pkgName=starcal3
 
 options=`getopt -o 'v' --long 'prefix:,verbose' -n "$0" -- "$@"`
 if [ $? != 0 ] ; then
-    printUsage
-    exit 1
+	printUsage
+	exit 1
 fi
 eval set -- "$options" ## Note the quotes around $options are essential!
 options=""
@@ -28,47 +28,47 @@ while true ; do
 done
 
 if [ -n "$1" ] ; then ## extra arguments
-    printUsage
-    exit 1
+	printUsage
+	exit 1
 fi
 
 if [ -z "$prefix" ] ; then ## prefix is empty (not been set)
-    prefix=/usr/local
-    for p in /usr/local /usr ; do
-        if [ -d $p/share/$pkgName ] ; then
-            prefix=$p
-            break
-        fi
-    done
+	prefix=/usr/local
+	for p in /usr/local /usr ; do
+		if [ -d $p/share/$pkgName ] ; then
+			prefix=$p
+			break
+		fi
+	done
 else
-    n=${#prefix}
-    if [ ${prefix:n-1:1} = / ] ; then
-        prefix=${prefix::-1}
-    fi
+	n=${#prefix}
+	if [ ${prefix:n-1:1} = / ] ; then
+		prefix=${prefix::-1}
+	fi
 fi
 
 shareDir="${prefix}/share"
 
 if [ -z $pkgName ] ; then ## do not f*** the system if pkgName was empty amiss!
-    echo "Internal Error! pkgName=''"
-    exit 1
+	echo "Internal Error! pkgName=''"
+	exit 1
 fi
 
 ##================== Starting to remove files =====================
 
 if [ -n "$verbose" ] ; then ## no output (note that quotation around $verbose is needed)
-    RM="rm -Rfv"
+	RM="rm -Rfv"
 else
-    RM="rm -Rf"
+	RM="rm -Rf"
 fi
 
 
 if [ -d "${shareDir}/$pkgName" ] ; then
-    $RM "${shareDir}/$pkgName"
+	$RM "${shareDir}/$pkgName"
 fi
 
 if [ -d "${shareDir}/doc/$pkgName" ] ; then
-    $RM "${shareDir}/doc/$pkgName"
+	$RM "${shareDir}/doc/$pkgName"
 fi
 
 ## what about the /etc/$pkgName and /var/log/$pkgName ## FIXME
