send errors to stderr (instead of stdout) in install* scripts

diff --git a/install b/install
--- a/install
+++ b/install
@@ -34,7 +34,7 @@ for PY_TMP in "${PY_SUPPORTED[@]}" ; do
 	PY=`which "python$PY_TMP"` && break
 done
 if [ -z "$PY" ] ; then
-	echo "Only these python version are supported: ${PY_SUPPORTED[@]}"
+	echo "Only these python version are supported: ${PY_SUPPORTED[@]}" >&2
 	exit 1
 fi
 
@@ -63,7 +63,7 @@ while true ; do
 		--prefix) prefix="$2" ; shift 2 ;;
 		--python) PY="$2" ; shift 2 ;;
 		--) shift ; break ;;
-		*) echo "Internal error!" ; exit 1 ;;
+		*) echo "Internal error!" >&2 ; exit 1 ;;
 	esac
 done
 
@@ -87,7 +87,7 @@ fi
 
 ## do not f*** the system if a variable was empty amiss!
 if [ -z $pkgName ] ; then
-	echo "Internal Error! pkgName=''"
+	echo "Internal Error! pkgName=''" >&2
 	exit 1
 fi
 if [ -z "$prefix" ] ; then ## prefix is empty (not been set)
diff --git a/install-fedora b/install-fedora
--- a/install-fedora
+++ b/install-fedora
@@ -7,7 +7,7 @@ set -e
 
 
 if [ "$UID" != "0" ] ; then
-  echo "Run this script as root"
+  echo "Run this script as root" >&2
   exit 1
 fi
 
@@ -90,19 +90,19 @@ and Indian National calendars, as well as common English(Gregorian) calendar
 rpmbuild -bb $pkgName.spec
 status=$?
 if [ "$status" != "0" ] ; then
-    echo "rpmbuild exited with failed status '$status'"
+    echo "rpmbuild exited with failed status '$status'" >&2
     exit $status
 fi
 
 pkgPath="$HOME/rpmbuild/RPMS/noarch/$pkgName-$version-1.noarch.rpm"
 
 if [ ! -f $pkgPath ] ; then
-    echo "rpmbuild exited with success status $status, but no package file was found"
+    echo "rpmbuild exited with success status $status, but no package file was found" >&2
     exit 1
 fi
 
 if [ ! -f $pkgPath ] ; then
-    echo "Package file $pkgPath does not exit"
+    echo "Package file $pkgPath does not exit" >&2
     exit 1
 fi
 
diff --git a/install-suse b/install-suse
--- a/install-suse
+++ b/install-suse
@@ -17,7 +17,7 @@ function check_pkg(){
 }
 
 if [ "$UID" != "0" ] ; then
-  echo "Run this script as root"
+  echo "Run this script as root" >&2
   exit 1
 fi
 
@@ -108,11 +108,11 @@ pkgPath="`ls /usr/src/packages/RPMS/noarch/$pkgName*$version*.rpm`"
 echo "pkgPath=$pkgPath"
 
 if [ -z "$pkgPath" ] ; then
-    echo "Package build failed"
+    echo "Package build failed" >&2
     exit 1
 fi
 if [ ! -f "$pkgPath" ] ; then
-    echo "Package file $pkgPath does not exit"
+    echo "Package file $pkgPath does not exit" >&2
     exit 1
 fi
 
