fix non-working uninstall script (it just exited after parsing args) also fix shellcheck errors

diff --git a/distro/base/uninstall b/distro/base/uninstall
--- a/distro/base/uninstall
+++ b/distro/base/uninstall
@@ -7,7 +7,8 @@ function printUsage {
 pkgName=starcal3
 
 
-if options=$(getopt -o 'v' --long 'prefix:,verbose' -n "$0" -- "$@") ; then
+if ! options=$(getopt -o 'v' --long 'prefix:,verbose' -n "$0" -- "$@") ; then
+	echo "Error parsing arguments and flags" >&2
 	printUsage
 	exit 1
 fi
@@ -28,6 +29,7 @@ while true ; do
 done
 
 if [ -n "$1" ] ; then ## extra arguments
+	echo "Too many arguments" >&2
 	printUsage
 	exit 1
 fi
@@ -42,7 +44,7 @@ if [ -z "$prefix" ] ; then ## prefix is empty (not been set)
 	done
 else
 	n=${#prefix}
-	if [ ${prefix:n-1:1} = / ] ; then
+	if [ "${prefix:n-1:1}" = / ] ; then
 		prefix=${prefix::-1}
 	fi
 fi
@@ -74,9 +76,9 @@ fi
 ## what about the /etc/$pkgName and /var/log/$pkgName ## FIXME
 
 $RM /etc/init.d/*${pkgName}d* /etc/rc.d/*${pkgName}d* 2>/dev/null ## FIXME
-$RM $shareDir/$pkgName/icons/hicolor/*/apps/$pkgName.png 2>/dev/null
-$RM $prefix/bin/$pkgName $prefix/bin/$pkgName-qt 2>/dev/null
-$RM $shareDir/applications/$pkgName.desktop 2>/dev/null
-$RM $prefix/share/locale/*/LC_MESSAGES/$pkgName.mo 2>/dev/null
+$RM "$shareDir/$pkgName/icons/hicolor/"*"/apps/$pkgName.png" 2>/dev/null
+$RM "$prefix/bin/$pkgName" 2>/dev/null
+$RM "$shareDir/applications/$pkgName.desktop" 2>/dev/null
+$RM "$prefix/share/locale/"*"/LC_MESSAGES/$pkgName.mo" 2>/dev/null
 
 
